services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
        - NEXT_PUBLIC_AUTH_API_URL=http://localhost:8001/api/v1/auth
        - NEXT_PUBLIC_APP_URL=http://localhost:3000
        - NEXT_PUBLIC_APP_NAME=Imobly
        - NEXT_PUBLIC_APP_VERSION=1.0.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:8001/api/v1/auth
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - imovel_network

networks:
  imovel_network:
    external: true